[package]
name = "demoparser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "demoparser"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17", features = ["extension-module"] }
bitreader = "0.3.6"
protobuf = "3.1.0"
numpy = "0.17.1"
fxhash = "0.2.1"
hashbrown = "0.12.3"
flate2 = "1.0.24"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
ndarray = "0.15.6"
polars = "0.24.3"
polars-arrow = "0.24.3"
csv = "1.1"


[dependencies.csgoproto]
path = "./csgoproto"
[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.3.2"



[profile.dev]
overflow-checks = false

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
jemallocator = "0.3.2"
debug = true
